In [3]:
import numpy as np
import pandas as pd

### Series from lists

In [ ]:
# string

country = ['India','USA','Srilanka']
pd.Series(country)

0       India
1         USA
2    Srilanka
dtype: object

In [4]:
# intergers

score = [12,3,2,3,2,53]
pd.Series(score)

0    12
1     3
2     2
3     3
4     2
5    53
dtype: int64

In [5]:
# custom indexes

marks = [23,66,39,77]
subjects = ['Maths','English','Physics','Chemistry']

pd.Series(marks, index=subjects)

Maths        23
English      66
Physics      39
Chemistry    77
dtype: int64

In [4]:
# series with dictionary

s = {
    'maths':27,
    'english':88,
    'Science': 56,
    'Hindi':98
}

marks = pd.Series(s)
marks

maths      27
english    88
Science    56
Hindi      98
dtype: int64

### Pandas Series Attributes

In [8]:
s = pd.Series([10,20,30,40,None], index=['a','b','c','d','e'])

# Attributes

print("Index of the Series: ",s.index)
print("Values In the Series: ",s.values)
print("Data type of the Series: ",s.dtype)
print("Size of the series: ",s.size)
print("Shape of the Series: ",s.shape)
print("check NaN values in Series: ",s.hasnans)
print("Check that Series has unqiue values or not: ",s.is_unique)
print("check number of Dimensions of Series: ",s.ndim)
print("Check that Series is empty or not: ",s.empty)

Index of the Series:  Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Values In the Series:  [10. 20. 30. 40. nan]
Data type of the Series:  float64
Size of the series:  5
Shape of the Series:  (5,)
check NaN values in Series:  True
Check that Series has unqiue values or not:  True
check number of Dimensions of Series:  1
Check that Series is empty or not:  False

### Series Using read_csv()

In [11]:
## With one column,

subscribers = pd.read_csv('subs.csv')
subscribers

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [20]:
## with two columns,,

vk =pd.read_csv('kohli_ipl.csv',index_col='match_no')
vk

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

### Series Method

In [14]:
## Head ans Tail

subscribers.head()

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [15]:
subscribers.tail()

     Subscribers gained
360                 231
361                 226
362                 155
363                 144
364                 172

In [16]:
subscribers.head(10)

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44
5                  46
6                  33
7                  40
8                  44
9                  74

In [17]:
movies = pd.read_csv('bollywood.csv', index_col='movie')
movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [21]:
## Value count,

movies.value_counts()

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Aashish Bhatt        1
Abhimanyu Dasani     1
Abhishek Bharate     1
Adhvik Mahajan       1
Aditya Narayan       1
Name: count, Length: 566, dtype: int64

In [25]:
# Sort values,

vk.sort_values()

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'