In [1]:
import pandas as pd
import numpy as np

In [2]:
courses = pd.read_csv('courses.csv')
bolly = pd.read_csv('bollywood.csv')
deli = pd.read_csv('deliveries.csv')
nov = pd.read_csv('reg-month1.csv')
dec = pd.read_csv('reg-month2.csv')
students = pd.read_csv('students.csv')

In [3]:
nov.head(2)

   student_id  course_id
0          23          1
1          15          5

In [4]:
courses.head(2)

   course_id course_name  price
0          1      python   2499
1          2         sql   3499

In [5]:
deli.head(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [6]:
dec.head(2)

   student_id  course_id
0           3          5
1          16          7

In [7]:
students.head(2)

   student_id           name  partner
0           1  Kailash Harjo       23
1           2    Esha Butala        1

In [8]:
bolly.head(2)

                      movie           lead
0  Uri: The Surgical Strike  Vicky Kaushal
1             Battalion 609    Vicky Ahuja

In [4]:
##

cc = pd.merge(courses,nov,on='course_id',how='left')
cc['course_name'].value_counts()

course_name
python              6
data analysis       4
machine learning    3
power bi            3
ms sxcel            2
tableau             2
pyspark             2
sql                 1
pandas              1
plotly              1
Numpy               1
C++                 1
Name: count, dtype: int64

In [9]:
reg = pd.concat([nov,dec], ignore_index=True)

In [ ]:
## find the total revenue generated,

total_revenue = (pd.merge(reg,courses,on='course_id',how='inner'))
int(total_revenue['price'].sum())

154247

In [16]:
## find the revenue generated month by month,

for_nov = pd.merge(nov,courses,on='course_id',how='inner')['price'].sum()
for_dec = pd.merge(dec,courses, on='course_id',how='inner')['price'].sum()

print("Total revenue in November: ",for_nov)
print("Total revenue in December: ",for_dec)

Total revenue in November:  89175
Total revenue in December:  65072

In [20]:
## another way for this question,,

temp_df = pd.concat([nov,dec],keys=['NOV','DEC']).reset_index()
rev = pd.merge(temp_df,courses,on='course_id').groupby('level_0')['price'].sum()
rev

level_0
DEC    65072
NOV    89175
Name: price, dtype: int64

In [32]:
## Print the registration table,,
# columns --> name -> course -> price.

reg_table = pd.merge(reg,students,on='student_id')
dd = reg_table.merge(courses,on='course_id')
del dd['partner']
dd

    student_id  course_id                name       course_name  price
0           23          1      Chhavi Lachman            python   2499
1           15          5           Preet Sha           tableau   2499
2           18          6     Fardeen Mahabir          power bi   1899
3           23          4      Chhavi Lachman  machine learning   9999
4           16          9        Elias Dodiya            plotly    699
5           18          1     Fardeen Mahabir            python   2499
6            1          1       Kailash Harjo            python   2499
7            7          8        Tarun Thaker            pandas   1099
8           22          3          Yash Sethi     data analysis   4999
9           15          1           Preet Sha            python   2499
10          19          4        Qabeel Raman  machine learning   9999
11           1          6       Kailash Harjo          power bi   1899
12           7         10        Tarun Thaker           pyspark   2499
13          11          7  David Mukhopadhyay          ms sxcel   1599
14          13          3      Munni Varghese     data analysis   4999
15          24          4        Radhika Suri  machine learning   9999
16          21          1          Seema Kota            python   2499
17          16          5        Elias Dodiya           tableau   2499
18          23          3      Chhavi Lachman     data analysis   4999
19          17          7        Yasmin Palan          ms sxcel   1599
20          23          6      Chhavi Lachman          power bi   1899
21          25          1     Shashank D’Alia            python   2499
22          19          2        Qabeel Raman               sql   3499
23          25         10     Shashank D’Alia           pyspark   2499
24           3          3      Parveen Bhalla     data analysis   4999
25           3          5      Parveen Bhalla           tableau   2499
26          16          7        Elias Dodiya          ms sxcel   1599
27          12         10          Radha Dutt           pyspark   2499
28          12          1          Radha Dutt            python   2499
29          14          9    Pranab Natarajan            plotly    699
30           7          7        Tarun Thaker          ms sxcel   1599
31           7          2        Tarun Thaker               sql   3499
32          16          3        Elias Dodiya     data analysis   4999
33          17         10        Yasmin Palan           pyspark   2499
34          11          8  David Mukhopadhyay            pandas   1099
35          14          6    Pranab Natarajan          power bi   1899
36          12          5          Radha Dutt           tableau   2499
37          12          7          Radha Dutt          ms sxcel   1599
38          18          8     Fardeen Mahabir            pandas   1099
39           1         10       Kailash Harjo           pyspark   2499
40           1          9       Kailash Harjo            plotly    699
41           2          5         Esha Butala           tableau   2499
42           7          6        Tarun Thaker          power bi   1899
43          22          5          Yash Sethi           tableau   2499
44          22          6          Yash Sethi          power bi   1899
45          23          9      Chhavi Lachman            plotly    699
46          23          5      Chhavi Lachman           tableau   2499
47          14          4    Pranab Natarajan  machine learning   9999
48          14          1    Pranab Natarajan            python   2499
49          11         10  David Mukhopadhyay           pyspark   2499