In [2]:
import pandas as pd

In [23]:
df = pd.read_csv('startup_funding.csv')

In [25]:
df.head(3)

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN

In [26]:
## Dropping Remarks Column,

df.drop(columns=['Remarks'],inplace=True)

In [27]:
## Setting Sr No as Index,

df.set_index('Sr No')

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"
...,...,...,...,...,...,...,...,...
3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000"
3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000"
3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000"
3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN
3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000"

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
dtypes: int64(1), object(8)
memory usage: 214.2+ KB

In [29]:
# Rename columns,
df.rename(columns={
    'Date dd/mm/yyyy':'Date',
    'Startup Name':'Startups',
    'City  Location':'City',
    'Investors Name':'Investors',
    'InvestmentnType':'Investment Type',
    'Amount in USD':'Amount'
}, inplace=True)

In [30]:
df['Amount'].dtype

dtype('O')

In [31]:
df['Amount'] = df['Amount'].str.replace(',','',regex=False)

In [32]:
df

,Sr No,Date,Startups,Industry Vertical,SubVertical,City,Investors,Investment Type,Amount
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000
...,...,...,...,...,...,...,...,...,...
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,4500000
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,825000
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,140000

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date               3044 non-null   object
 2   Startups           3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City               2864 non-null   object
 6   Investors          3020 non-null   object
 7   Investment Type    3040 non-null   object
 8   Amount             2084 non-null   object
dtypes: int64(1), object(8)
memory usage: 214.2+ KB

In [34]:
## first dropping all NaN rows,

df = df.dropna(subset=['Date','Startups','Industry Vertical','SubVertical','City','Investors','Investment Type','Amount'])

In [35]:
df

,Sr No,Date,Startups,Industry Vertical,SubVertical,City,Investors,Investment Type,Amount
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000
...,...,...,...,...,...,...,...,...,...
2098,2099,29/01/2016,Qriyo,Consumer Internet,Online Fitness & Educational information Aggre...,Jodhpur,Idein Ventures,Seed Funding,160000
2100,2101,29/01/2016,Aisle,Consumer Internet,Indians focused Matchmaking App,Bangalore,"TermSheet, ah! Ventures",Seed Funding,185000
2101,2102,29/01/2016,FreshMenu,Consumer Internet,Fresh Food Delivery platform,Bangalore,"Zodius Technology Fund, Lightspeed Venture Par...",Private Equity,17000000
2102,2103,29/01/2016,Truebil,ECommerce,Online marketplace for cars,Mumbai,"Kalaari Capital, Inventus Capital, Tekton Vent...",Private Equity,5150000
2103,2104,29/01/2016,Rare Media,Technology,Mobile & Cloud based App developer,New Delhi,Info Edge (India) Ltd,Private Equity,1100000

In [39]:
df = df[df['Amount'].str.isdigit()]

In [40]:
df['Amount'] = df['Amount'].astype('float')

C:\Users\MAHAKAAL\AppData\Local\Temp\ipykernel_20468\3718911808.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Amount'] = df['Amount'].astype('float')

In [41]:
df

,Sr No,Date,Startups,Industry Vertical,SubVertical,City,Investors,Investment Type,Amount
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000.0
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394.0
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860.0
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000.0
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000.0
...,...,...,...,...,...,...,...,...,...
2098,2099,29/01/2016,Qriyo,Consumer Internet,Online Fitness & Educational information Aggre...,Jodhpur,Idein Ventures,Seed Funding,160000.0
2100,2101,29/01/2016,Aisle,Consumer Internet,Indians focused Matchmaking App,Bangalore,"TermSheet, ah! Ventures",Seed Funding,185000.0
2101,2102,29/01/2016,FreshMenu,Consumer Internet,Fresh Food Delivery platform,Bangalore,"Zodius Technology Fund, Lightspeed Venture Par...",Private Equity,17000000.0
2102,2103,29/01/2016,Truebil,ECommerce,Online marketplace for cars,Mumbai,"Kalaari Capital, Inventus Capital, Tekton Vent...",Private Equity,5150000.0
2103,2104,29/01/2016,Rare Media,Technology,Mobile & Cloud based App developer,New Delhi,Info Edge (India) Ltd,Private Equity,1100000.0

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1397 entries, 0 to 2103
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              1397 non-null   int64
 1   Date               1397 non-null   object
 2   Startups           1397 non-null   object
 3   Industry Vertical  1397 non-null   object
 4   SubVertical        1397 non-null   object
 5   City               1397 non-null   object
 6   Investors          1397 non-null   object
 7   Investment Type    1397 non-null   object
 8   Amount             1397 non-null   float64
dtypes: float64(1), int64(1), object(7)
memory usage: 109.1+ KB

In [42]:
def to_inr(dollar):
    inr = dollar * 95.8
    return inr/10000000

In [44]:
df['Amount'] = df['Amount'].apply(to_inr)

C:\Users\MAHAKAAL\AppData\Local\Temp\ipykernel_20468\1748484589.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Amount'] = df['Amount'].apply(to_inr)

In [45]:
df

,Sr No,Date,Startups,Industry Vertical,SubVertical,City,Investors,Investment Type,Amount
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1916.000000
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,77.103615
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,175.877879
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.740000
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,17.244000
...,...,...,...,...,...,...,...,...,...
2098,2099,29/01/2016,Qriyo,Consumer Internet,Online Fitness & Educational information Aggre...,Jodhpur,Idein Ventures,Seed Funding,1.532800
2100,2101,29/01/2016,Aisle,Consumer Internet,Indians focused Matchmaking App,Bangalore,"TermSheet, ah! Ventures",Seed Funding,1.772300
2101,2102,29/01/2016,FreshMenu,Consumer Internet,Fresh Food Delivery platform,Bangalore,"Zodius Technology Fund, Lightspeed Venture Par...",Private Equity,162.860000
2102,2103,29/01/2016,Truebil,ECommerce,Online marketplace for cars,Mumbai,"Kalaari Capital, Inventus Capital, Tekton Vent...",Private Equity,49.337000
2103,2104,29/01/2016,Rare Media,Technology,Mobile & Cloud based App developer,New Delhi,Info Edge (India) Ltd,Private Equity,10.538000

In [50]:
# converting Date colum to DateTime object,

df['Date'] = pd.to_datetime(df['Date'],errors='coerce')

C:\Users\MAHAKAAL\AppData\Local\Temp\ipykernel_20468\4073287414.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'],errors='coerce')

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1397 entries, 0 to 2103
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              1397 non-null   int64
 1   Date               607 non-null    datetime64[ns]
 2   Startups           1397 non-null   object
 3   Industry Vertical  1397 non-null   object
 4   SubVertical        1397 non-null   object
 5   City               1397 non-null   object
 6   Investors          1397 non-null   object
 7   Investment Type    1397 non-null   object
 8   Amount             1397 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 109.1+ KB

In [52]:
df

,Sr No,Date,Startups,Industry Vertical,SubVertical,City,Investors,Investment Type,Amount
0,1,2020-09-01,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1916.000000
1,2,NaT,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,77.103615
2,3,2020-09-01,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,175.877879
3,4,2020-02-01,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.740000
4,5,2020-02-01,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,17.244000
...,...,...,...,...,...,...,...,...,...
2098,2099,NaT,Qriyo,Consumer Internet,Online Fitness & Educational information Aggre...,Jodhpur,Idein Ventures,Seed Funding,1.532800
2100,2101,NaT,Aisle,Consumer Internet,Indians focused Matchmaking App,Bangalore,"TermSheet, ah! Ventures",Seed Funding,1.772300
2101,2102,NaT,FreshMenu,Consumer Internet,Fresh Food Delivery platform,Bangalore,"Zodius Technology Fund, Lightspeed Venture Par...",Private Equity,162.860000
2102,2103,NaT,Truebil,ECommerce,Online marketplace for cars,Mumbai,"Kalaari Capital, Inventus Capital, Tekton Vent...",Private Equity,49.337000
2103,2104,NaT,Rare Media,Technology,Mobile & Cloud based App developer,New Delhi,Info Edge (India) Ltd,Private Equity,10.538000

In [55]:
sorted(set(df['Investors'].str.split(',').sum()))

['',
 ' & Others',
 ' 100 Co-founders Lab and others.',
 ' 122 West Ventures',
 ' 1Crowd',
 ' 3ONE4 Capital Advisors',
 ' 3one4 Capital',
 ' 3one4 Capital Advisors LLP',
 ' 500 Start-Ups',
 ' 500 Startups',
 ' 91SpringBoard',
 ' 91springboard',
 ' ABB Technology Ventures',
 ' ABCOM Investments',
 ' AET Fund',
 ' AL Nour International Holdings and Mark V Investments',
 ' Aarin Capital',
 ' Abhai S. Rao',
 ' Abhay Singhal',
 ' Abhishek Acharya',
 ' Abhishek Goyal',
 ' Abhishek Jain',
 ' Abstract Ventures',
 ' Abu Farhan Azmi',
 ' Accel',
 ' Accel India',
 ' Accel Partner',
 ' Accel Partners',
 ' Accel Partners & Raghunandan Gangappa',
 ' Accel Partners RNT Associates',
 ' Accel Partners and G Raghunandan',
 ' Accel Partners and IDG Ventures',
 ' Accel Partners and Saama Capital',
 ' Accel Partners and Tiger Global Management.',
 ' Acumen Fund',
 ' Adi Saravanan',
 ' Aditya Agarwal',
 ' Aditya Malik & Others',
 ' Aditya Verma',
 ' Aditya Vij',
 ' AdvantEdge Partners',
 ' Adveq Management',
 ' Ajay Bhatia',
 ' Ajay Modani',
 ' Akash Garg',
 ' Akatsuki and Incubate Fund from Japan and Better Capital AngelList syndicate.',
 ' Alfa Capital',
 ' Alok Mittal and Sachin Bhatia',
 ' Alphabet\\\\xe2\\\\x80\\\\x99s growth investment arm Capital G and Axis Bank',
 ' Altimeter Capital',
 ' Alto Partners',
 ' Amar Arsikere',
 ' Ambarish Gupta',
 ' Ameera Shah',
 ' Amereus Group',
 ' American Express Ventures',
 ' Amit Gupta',
 ' Amit Jindal',
 ' Amit Khanna',
 ' Amit Nagar',
 ' Amit Nanavati',
 ' Amit Singal',
 ' Amit Sinha',
 ' Amiya Pathak',
 ' Anand Chandrasekaran',
 ' Anand Ladsariya',
 ' Anand Mahindra',
 ' Anand Rajaraman',
 ' Ananda Kallugadde',
 ' Anandbir Singh',
 ' Ananth Narayanan',
 ' Anbu Pandian',
 ' Andre Hoffman',
 ' Aneesh Reddy',
 ' Anil Jaggia',
 ' Anirudh Damani',
 ' Anirudh Rastogi',
 ' Anirudh Sheth',
 ' Anish K',
 ' Anisha Mittal',
 ' Anita Hassanandani',
 ' Anjali Bansal',
 ' Anjani Prasad',
 ' Ankit Aditya',
 ' Ankit Bhati',
 ' Ankit Sharma and others',
 ' Ankur Capital',
 ' Ankur Singla',
 ' Ankur Warikoo',
 ' Ankush Gupta',
 ' Anshoo Gaur',
 ' Anshu Bahadur',
 ' Anshuman Das',
 ' Anthill Scale Ventures',
 ' Anthill Ventures',
 ' Anuj Sanghi',
 ' Anuj Srivastava',
 ' Anupam Mittal',
 ' Anurag Srivastava',
 ' Apoorva Patni',
 ' Aprameya Radhakrishna',
 ' Aprameya Radhakrishnan',
 ' Apurva Salapuria',
 ' Aqeel Ahmed',
 ' Aravind Sanka',
 ' Arihant Patni',
 ' Arihant Patni of Patni Family Office',
 ' Arjun Malhotra',
 ' Arjun Sharmaa',
 ' Arjun and Rohan Malhotra',
 ' Arkas Industries',
 ' Arthavida Ventures',
 ' Artiman Ventures',
 ' Arts Alliance',
 ' Arun Garg',
 ' Arun Malhotra',
 ' Arun Sarin',
 ' Ascent Capital',
 ' Ashish Agrawal',
 ' Ashish Chand',
 ' Ashish Dhawan',
 ' Ashish Goenka',
 ' Ashish Gupta',
 ' Ashish Hemrajani',
 ' Ashish Lakhanpal',
 ' Ashish Tulsian',
 ' Ashvin Chadha',
 ' Aspada',
 ' Aspada Investment',
 ' Aspada Ventures',
 ' Atul Goel',
 ' Axan Partners',
 ' Axan Venture',
 ' Axilor Partners',
 ' Axilor Ventures',
 ' Axilor Ventures and Binny Bansal',
 ' Axis Bank',
 ' Axis Capital',
 ' Axis Capital & Others',
 ' B Capital',
 ' BEENEXT',
 ' BVR Mohan Reddy',
 ' Badal Malick',
 ' Bamboo Capital Partners',
 ' Bank to the Future and Funders Club',
 ' Basab Pradhan',
 ' BeeNext',
 ' Beehive Capital Advisor',
 ' Beenext',
 ' Beenext Ventures',
 ' Beenos',
 ' Behram Vakil and Jerxis Vandrevala',
 ' Bennett Coleman & Co. Ltd',
 ' Bertelsmann India',
 ' Bertelsmann India Investments',
 ' Bessemer Venture Partners',
 ' Bharat Sheth',
 ' Bharat Vijay',
 ' Bharti Enterprises',
 ' Bhavish Aggarwal',
 ' Bhupender Singh',
 ' Bill & Melinda Gates Foundation',
 ' Binny Bansal',
 ' BizReach',
 ' Blacksoil',
 ' Blue Cloud Ventures',
 ' Blume Ventures',
 ' Blume Ventures & IvyCap Ventures',
 ' Blume Ventures & Vaibhav Domkundwar',
 ' Blume Ventures and Innoven Capital.',
 ' Blume Ventures.',
 ' Bobby Reddy',
 ' Bold Ventures',
 ' BookMyShow)',
 ' Boost VC',
 ' Burda Principal Investments',
 ' C31 Ventures',
 ' CCavenue',
 ' CDC Group',
 ' CRV',
 ' CSC Upshot & Angel investors',
 ' Capier Investments',
 ' CapitalG',
 ' Caspian and Hivos-Triodos Fund',
 ' Catamaran Ventures',
 ' Chennai Angels',
 ' Chidambaram Palaniappan',
 ' Chiratae Ventures',
 ' Chiratae Ventures (formerly IDG Ventures)',
 ' Cisco Ventures',
 ' Citrus Payments',
 ' Coleman and Co. Ltd (BCCL)',
 ' Coleman and Company Ltd',
 ' Contrarian Capital',
 ' Contrarian Vriddhi Fund',
 ' Cyber Carrier VC',
 ' CyberAgent Ventures',
 ' DG Incubation',
 ' DG Ventures India',
 ' DSG Consumer Partners',
 ' DSG Consumer Partners and Venture Nursery',
 ' DST Global',
 ' DST Partners and RPS Ventures',
 ' Dalip Pathak and Others',
 ' Daljit Singh',
 ' Darius Pandole',
 ' Darrin Capital',
 ' Das Capital and IT Farm',
 ' DeVry Inc',
 ' Deepak Natraj',
 ' Deepinder Goyal',
 ' Dena',
 ' Deobrat Singh',
 ' Deshe Holdings',
 ' Deutsche Telekom Strategic Investments (DTSI)',
 ' Dewan Housing Finance Corp',
 ' Dheerag Jain',
 ' Diaz Nesamoney',
 ' Digital Currency Group',
 ' Digital Garage',
 ' Digital Garage Inc',
 ' Dileep Nath',
 ' Dilip Khandwelwal from SAP Labs India',
 ' Dinesh Mittal',
 ' Dinesh R. Challa',
 ' Divyesh Shah',
 ' Dr V Ravinder',
 ' Dr. Aniruddha Malpani',
 ' Dr. Apoorv Ranjan Sharma',
 ' Dr. Ranjan Pai',
 ' Dr. Ritesh Malik',
 ' Draper Associates',
 ' Dream Incubator',
 ' E-City VEntures Atul Goel',
 ' EDBI',
 ' Edelweiss Private Equity',
 ' Edelweiss and Beenext',
 ' Eight Roads Ventures',
 ' Electronic Development Fund',
 ' Elevar Equity',
 ' Elevar Equity and Accel Partners',
 ' Elevate Sports',
 ' Emergent Ventures',
 ' Emergent Ventures and Y Combinator',
 ' Endiya Partners',
 ' Entrepreneurs India',
 ' Esvee Technologies Inc',
 ' Eureka Forbes Ltd',
 ' Evan Lim',
 ' Excelsior Investments',
 ' Exfinity Ventures',
 ' Existing investors',
 ' F-Prime Capital Partners',
 ' FAO Ventures',
 ' FIL Capital Management',
 ' FJ Labs',
 ' Faering Capital',
 ' Falcon Edge',
 ' Farhan Naqvi',
 ' Farooq Adam Mukadam',
 ' Fenqile',
 ' Fidelity Growth Partners India',
 ' Fireside Ventures',
 ' Flipkart',
 ' Florintree Advisors',
 ' Fortisure Ventures',
 ' Fosun RZ Capital',
 ' Founder Collective',
 ' Foxconn Technology Group',
 ' Franchise India Brands',
 ' FreshMenu)',
 ' Fullerton India Credit Company Ltd',
 ' Fundnel',
 ' Fusion Tech Ventures',
 ' GHV Accelerator',
 ' GREE Ventures',
 ' GREE Ventures and Summit Media',
 ' GVFL',
 ' Gagan Dugal',
 ' Ganpat Singhvi',
 ' Gaurav Bhalotia',
 ' Gaurav Marya',
 ' Gaurav Suri and Ankit Kesarwani',
 ' Girish Mathrubootham',
 ' Girnar Software',
 ' Globevestor',
 ' Globevestor & others',
 ' Gokul Rajaram',
 ' Goldbell Group',
 ' Goldman Sachs',
 ' Grace Capital Ventures',
 ' Great Oaks Ventures',
 ' Green Shots Capital',
 ' Greenoaks Capital',
 ' Greenoaks Capital Partners',
 ' Grey Orange',
 ' Grey Orange Robotics',
 ' Greycroft',
 ' Greycroft Partners',
 ' GrowX',
 ' GrowX Ventures',
 ' HDFC Asset Management',
 ' Hack VC',
 ' Haresh Chawla',
 ' Harminder Sahani',
 ' Harmony Partners',
 ' Harpreet Singh Grover',
 ' Harsh Mariwala',
 ' HealthQuad',
 ' HealthQuad and Fireside Ventures',
 ' Helion Venture',
 ' Helion Venture Partners',
 ' Helion Ventures',
 ' Hemant Kaul',
 ' Hemant Luthra',
 ' Hercules Capital',
 ' Hermes Group',
 ' Hero Electronix\\\\xe2\\\\x80\\\\x99s corporate financing arm',
 ' Hero Enterprise',
 ' Hetal Sonpal',
 ' Hillhouse Capital',
 ' Himanshu Aggarwal',
 ' Himanshu Aggrawal',
 ' Hinduja Leyland Finance and IntelleGrow',
 ' Hitesh Oberoi',
 ' Holtzbrink Ventures',
 ' Horizons Ventures',
 ' Hornbill Orchid India Fund',
 ' Hrishi Oberoi',
 ' Hyderabad Angels',
 ' IDFC-Parampara Capital',
 ' IDG Venture',
 ' IDG Ventures',
 ' IDG Ventures & Indian Angel Network',
 ' IDG Ventures India',
 ' IFC',
 ' IFMR',
 ' IIFL Wealth',
 ' ILearnFinance Academy Pvt. Ltd.',
 ' IMJ Investment Partners',
 ' IMM Investment',
 ' ITW Digital',
 ' Ideation Initiative Pvt. Ltd',
 ' Ignition Partners',
 ' Inc95 Consulting',
 ' India Alternatives',
 ' India Quotient',
 ' Indian Angel Network',
 ' Indian Angel Network (IAN)',
 ' Individual Investors',
 ' Infocomm Development Authority of Singapore',
 ' Infocomm Investments',
 ' Infosys Innovation Fund',
 ' Innogy',
 ' Innov8',
 ' Innoven Capital',
 ' IntelleGrow',
 ' International Finance Corporation (IFC)',
 ' Inventus Capital',
 ' Inventus Capital Partners',
 ' IvyCap Ventures',
 ' JLL',
 ' Jagdish & Sandeep Mehta Family Office',
 ' Jaspreet Bindra',
 ' Jatin Aneja',
 ' Jayant Davar',
 ' Jayesh Parekh',
 ' Jaysukh Sapra',
 ' Jeroen Mensen',
 ' Jitendra Gupta & Others',
 ' Joby Babu',
 ' Jungle Ventures',
 ' Jyoti Bansal',
 ' KCK Global & Others',
 ' KK Mehra',
 ' Kae Capital',
 ' Kae Capital & Others',
 ' Kalaari Capital',
 ' Kalaari Capital and IDG Ventures India',
 ' Kalaari Capital and Inventus Capital',
 ' Kalaari Capital and Others',
 ' Kalaari Capital and Private equity firm Multiples Alternate Asset Management',
 ' Kamal Chabra',
 ' Kanchan Ghoshal',
 ' Kapil Hetamsaria',
 ' Keiretsu Forum & Others',
 ' Khattar Holdings',
 ' Khosla Impact',
 ' Khosla Ventures',
 ' Kima Ventures',
 ' Kinzon Capital',
 ' Kiran Deshpande',
 ' Kishore Ganji',
 ' Kishore Kumar',
 ' Konly Venture',
 ' Kris Gopalakrishnan',
 ' Krish Seshadri',
 ' Krishnakumar Nataraj',
 ' Krishnakumar Natarajan',
 ' Kumar Vembu',
 ' Kunal Bahl',
 ' Kunal Khattar',
 ' Kunal Shah',
 ' Kunal Shah and Manish Patel.',
 ' L.D Sharma',
 ' LG Chandrasekhar',
 ' LGT Impact',
 ' LGT Impact Ventures',
 ' Lakshmi Narayanan',
 ' Lalit Mangal',
 ' Lasmer NV',
 ' Learn Capital',
 ' Let\\\\xe2\\\\x80\\\\x99s Venture',
 ' LetsVenture',
 ' LetsVenture & Others',
 ' LightStreet',
 ' Lightbox Expansion Fund',
 ' Lightbridge Partners & Kairos',
 ' Lightspeed US',
 ' Lightspeed Venture Partners',
 ' Lightspeed Ventures',
 ' Line Corp',
 ' Liquid 2 Ventures',
 ' Lomesh Agarwal',
 ' Lumina Datamatics',
 ' Lumis Partners',
 ' M George Oommen',
 ' M&S Partners',
 ' MEMG CDC',
 ' MEMG Family Office',
 ' MGV',
 ' MJ Aravind',
 ' Mahavir Sharma',
 ' Mahendra Doshi',
 ' Mahesh Kothurkar',
 ' Mahesh Murthy',
 ' Maheshwar Peri',
 ' Maheshwari Investments Pvt Ltd',
 ' Maiden Lane Ventures',
 ' MakeMyTrip',
 ' Mamoru Taniya',
 ' Mandhian family & Others',
 ' Manickam Mahalingam',
 ' Manish Prasad',
 ' Manish Shah',
 ' March Capital',
 ' Mariwala family',
 ' Mathew Cyriac',
 ' Matrix Partners',
 ' Matrix Partners India',
 ' Matrix Partners India and Zodius Capital',
 ' Maverick Capital Ltd and HBM Healthcare Investments Ltd',
 ' Maverick Capital Ventures',
 ' Mayank Mittal & Others',
 ' Mayank Singhal',
 ' Mayfield & Others',
 ' Mayfield Capital',
 ' Mayfield India',
 ' Mayfield Ventures',
 ' Mayur Abhaya',
 ' MediAssist',
 ' MediaTek',
 ' Mekin Maheshwari',
 ' Michael & Susan Dell Foundation',
 ' Michael Herzig',
 ' Michael and Susan Dell Foundation',
 ' Micro venture capital firm GEMS Partners and Others',
 ' Micromax Informatics',
 ' Milind Chaudhary',
 ' Mistletoe',
 ' Mitali Pawar',
 ' Mitesh Shah',
 ' Moksh Sports Ventures',
 ' Mountain Pine Capital',
 ' Mumbai Angel',
 ' Mumbai Angels',
 ' Murali Nair',
 ' Myntra) and Mitesh Shah (finance chief',
 ' N Squared Management LLC',
 ' NEA',
 ' NPTK',
 ' NR Narayana Murthy.',
 ' Nagendra Chaudhary',
 ' Nagendra Prasad Bhanuprakash',
 ' Nandan Nilekani',
 ' Nandan Nilekani\\\\xe2\\\\x80\\\\x99s NRJN Trust',
 ' Narayan Seshadri',
 ' Naver',
 ' Navjot Saini',
 ' Navneet Education and Mahavir Agency',
 ' Neelesh Bhatnagar',
 ' Neeraj Goenka',
 ' Neoplux Technology Fund',
 ' Network 18',
 ' New Enterprise Associates (NEA)',
 ' Newfort Capital',
 ' Nexus India Capital Advisors',
 ' Nexus Venture Partners',
 ' Nexus Venture Partners and Blume Ventures',
 ' Nexus Ventures',
 ' Nick Haulkoury',
 ' Nikhil G and Bhavesh P',
 ' Nikhil Golcha',
 ' Nilender Chauhan',
 ' Nirmal Singh',
 ' Nirupa Shankar',
 ' Nirvana Digital India Fund',
 ' Nirvana Digital Investment Holding',
 ' Nirvana Digital Investment Holding Co Ltd',
 ' Nishant Rao',
 ' Nitesh Pant',
 ' Nitin Agarwal',
 ' North Base Media',
 ' Norwest Venture Partners',
 ' Nyca Partners and Thomvest Ventures',
 ' ONCOTRUST and Medintel Services Pvt. Ltd',
 ' OPPO',
 ' Oikocredit',
 ' Omidyar Network',
 ' Omidyar Network and Accion Venture Labs',
 ' Omidyar Network and Kae Capital',
 ' Omidyar Network and Kaizen Private Equity also participated in the round',
 ' Omidyar Network and Shunwei Capital',
 ' Omidyar Network.',
 ' Omnivore',
 ' Ontario Teachers\\\\\'"',
 ' Orios Venture Partners',
 ' Orios Venture Partners and the IAN Fund',
 ' Others',
 ' P.V SIndhu',
 ' PS1 Venture and GlobalLogic co-founder Rajul Garg',
 ' PV Srinivasan',
 ' Pablo van den Bosch & Others',
 ' Palash Jain',
 ' Pallav Nadhani',
 ' Pankaj Gupta',
 ' Pankaj Kapoor',
 ' Pankaj Tripathi',
 ' Paragon Trust',
 ' Parekh Marine Transport',
 ' Parikshit Dar',
 ' Parmeshwar Sharma',
 ' Partech Ventures',
 ' Paul Bucche',
 ' Paula Ravindra Mariwala',
 ' Pavan Bakeri',
 ' Pavan Ongole',
 ' Perceptive Advisors',
 ' Peyush Bansal',
 ' Phanindra Sama',
 ' Pidilite Industries director Ajay Parekh',
 ' Pine Brook',
 ' PitchRight Venture',
 ' Powai Lake Ventures',
 ' Powerhouse Ventures',
 ' Powerhouse Ventures & Others',
 ' Prabhakar MR & Others',
 ' Pradeep Guha',
 ' Pranav Dedhia',
 ' Pranay Jivrajka',
 ' Prashant Gooty',
 ' Prashant Gupta and Others',
 ' Prathithi Investment Trust',
 ' Pratik Singhi',
 ' Pratithi Investment Trust',
 ' Praveer Kumar',
 ' Pravega Ventures',
 ' Pravin Dongre',
 ' Pravin Gandhi',
 ' Premji Invest',
 ' Prime Venture Partners',
 ' Prime Venture Partners and Others',
 ' Prime Venture Partners.',
 ' Prof. Ram Kumar Kakani & Others',
 ' Pullela Gopichand',
 ' Puneet Agarwal',
 ' Puneet Dalmia & Others',
 ' Puneet Motihar',
 ' Purnima Khandelwal',
 ' Qasar Younis',
 ' Qualcomm',
 ' Qualcomm Venture',
 ' Qualcomm Ventures',
 ' Qualgro',
 ' Qualgro.',
 ' Quarizon',
 ' Quintillion Media',
 ' Quona Capital',
 ' R Ranganathan',
 ' R. Natarajan',
 ' RB International',
 ' RB Investments',
 ' RB Investments & existing investors',
 ' RB investments & Others',
 ' RNT Capital',
 ' RSI Fund',
 ' Radhakrishan Damani and Rakesh Jhunjhunwala',
 ' Raghunandan G',
 ' Rahul Agarwal',
 ' Rahul Kayan',
 ' Rahul Khanna',
 ' Rahul Maroli',
 ' Rahul Mehta',
 ' Rahul Singh',
 ' Rainforest Ventures',
 ' Rainmatter',
 ' Raj Y',
 ' Rajan Anandan',
 ' Rajan Anandan from Google',
 ' Rajan Pandhare',
 ' Rajat Gupta & Others',
 ' Rajeev Arora and Ram Ramsundar.',
 ' Rajeev Menon',
 ' Rajeev Mudumba',
 ' Rajesh Arora',
 ' Rajesh Balpande',
 ' Rajesh K Murthy',
 ' Rajesh Mahajan',
 ' Rajesh Ramaiah',
 ' Rajesh Ranavat',
 ' Rajesh Yohanan and Rahul Garg',
 ' Rajesh Yohannan',
 ' Rajiv Solanki',
 ' Rajul Garg',
 ' Rajul Jain',
 ' Rakesh Agrawal',
 ' Rakesh Desai',
 ' Rakesh Gakhar',
 ' Rakesh Malhotra',
 ' Rakesh Mathur',
 ' Rakesh and Rajesh Jhunjhunwala',
 ' Raksul',
 ' Ram Kumar Kakani',
 ' Rama Krishna Reddy',
 ' Ramana Thumu',
 ' Ranjan Sharma',
 ' Ratan Tata',
 ' Raveen Sastry (co-founder',
 ' Ravi Bhardwaj',
 ' Ravi Garikipati',
 ' Ravi Nigam & Others',
 ' Ravikanth Reddy',
 ' Real Time Ventures',
 ' Real Time Ventures.',
 ' Rebright Partners',
 ' Renaud Laplanche',
 ' Renuka Ramanath',
 ' Ribbit Capital',
 ' Ribbit Capital and Omidyar Network',
 ' Rishi Das',
 ' Rishi Gupta & Others',
 ' Ritesh Vohra',
 ' Rocketship',
 ' Rohan Desai and Paras Patel',
 ' Rohan Malhotra',
 ' Rohit',
 ' Rohit Bansal',
 ' Rohit Jain',
 ' Rohit MA',
 ' Romulus Capital and Kalaari Capital',
 ' Rosy Blue Securities',
 ' Roy Kwan',
 ' RuNet South Asia',
 ' Ruchi Sanghvi & others',
 ' Russian venture capital fund Ru-Net',
 ' S Chand Group',
 ' S Gopal',
 ' S Somasegar',
 ' SAIF Partners',
 ' SAIF Partners and Kalaari capital',
 ' SAIF Partners and LGT Impact Ventures',
 ' SAR Group',
 ' SCM Holdings',
 ' SIDBI Venture Capital',
 ' SRI Capital',
 ' Saama Capital',
 ' Sabre Partners and Neoplux',
 ' Sachin Bansal',
 ' Sachin Bhatia',
 ' Saha Fund',
 ' Saha fund Partners',
 ' Sailender Solanki',
 ' Saket Dhankar',
 ' Saket Kumar',
 ' Salesforce Ventures',
 ' Samar Singla',
 ' Sameer Narayan & Others',
 ' Samih Toukan and Hussam Khoury',
 ' Sandeep Gupta',
 ' Sandeep Mathur',
 ' Sandeep Raju',
 ' Sandeep Seerapu',
 ' Sandeep Tandon',
 ' Sands Capital and International Finance Corporation',
 ' Sanjay Mehta & Others',
 ' Sanjay Sathe',
 ' Sanjay Singh',
 ' Sanjiv Mittal',
 ' Sanjiv Rangrass',
 ' Sarath Sura',
 ' Sarbvir Singh',
 ' Sarthak and Nihit Agarwal',
 ' Sashi Reddi',
 ' Satish Khanna and Taparia family office.',
 ' Sattva Capital',
 ' Satya Muthyala',
 ' Saurab Paruthi',
 ' Saurabh Arora',
 ' Scott Banister',
 ' SeedPlus',
 ' Sequoia',
 ' Sequoia Capital',
 ' Sequoia Capital & Matrix Partners',
 ' Sequoia Capital India',
 ' Sequoia Capital India Advisors',
 ' Sequoia India',
 ' Shailesh Rao',
 ' Shanti Mohan',
 ' Shapoorji Pallonji & Co. Ltd.',
 ' Sharad Sharma & 14 others',
 ' Shardul Amarchand Mangaldas',
 ' Shinhan Bank and TS Investment',
 ' Shireesh Palle',
 ' Shobhit Shukla',
 ' Shreyans Shah',
 ' Shubham Gupta',
 ' Shuchin Bajaj',
 ' Shun Yoshida & Others',
 ' Shunwei Capital',
 ' Siddhivinayak Skyscrapers',
 ' Sidharth Pansari',
 ' Sidharth Rao',
 ' Sidhartha Hazarika & Others',
 ' Silicon Valley Bank',
 ' Simile Ventures',
 ' Singapore',
 ' Singapore Angel Network',
 ' Singapore Angel Network.',
 ' Singularity Holdings',
 ' Singularity Ventures',
 ' Singularity Ventures and Ravi Dhariwal',
 ' Sistema Asia Fund',
 ' Sistema JSFC and Tanncam Investment',
 ' Sixth Sense',
 ' Snehal Mantri',
 ' Social Capital',
 ' Sofina',
 ' Sofina s.a.',
 ' SoftBank Group',
 ' Softbank Group',
 ' Softbank\\\\xe2\\\\x80\\\\x99s DeepCore.',
 ' Soham Vencaps',
 ' Sol Primero',
 ' Sourav Ganguly',
 ' Space Matrix',
 ' Sparknext',
 ' Spiral Ventures',
 ' Spring Canter Investment Ltd.',
 ' Sreepathy Viswanathan',
 ' Stanford Angels',
 ' Startupxseed Ventures LLP',
 ' Steadview Capital',
 ' Steelhead Ventures & Others',
 ' Stelcore Management Services',
 ' Stellaris Venture Partners',
 ' Stellaris Venture Partners and Mayur Abhaya Srisrimal',
 ' Subba Rao Telidevara',
 ' Subho Ray and Samir Kumar',
 ' Subramanian Ramadorai',
 ' Sudhir Anandarao',
 ' Sudhir Mallem',
 ' Suhail Rahman',
 ' Sujeet Kumar',
 ' Sumit Jain',
 ' Summit Media',
 ' Suncoast Investments',
 ' Sundeep Sahni',
 ' Sundeep Singh Sahni',
 ' Sunil Goyal Ashish Gupta',
 ' Sunil Munjal',
 ' Sunil Singh & Others',
 ' Sunjay Kapoor and Telama Investment',
 ' Suramya Gupta',
 ' Suresh Shankar',
 ' Suresh Venkat',
 ' Surot Chatterjee',
 ' Susa Ventures',
 ' Susquehanna International Group.\\\\xc2\\\\xa0 Wavemaker Partners',
 ' Sutter Hill Ventures',
 ' Sven Hensen',
 ' Swastika Company Ltd',
 ' Syngenta AG',
 ' TCI Ventures',
 ' TPG Growth',
 ' TV Mohandas Pai',
 ' Tara India Fund IV and others',
 ' Taranjit Jaswal',
 ' Tarun Joshi',
 ' Tarun Khandelwal',
 ' Tashwinder Singh',
 ' Tata Group\\\\xe2\\\\x80\\\\x99s watch and jewellery retailing firm',
 ' Taurus Value Creation',
 ' Techstars Ventures & Others',
 ' Tekton Ventures',
 ' Tenaya Capital',
 ' Tencent Holdings',
 ' The Chennai Angels',
 ' The Grover Trust',
 ' The HR Fund',
 ' The Rise Fund & Others',
 ' The Syndicate Fund',
 ' Thrive Capital',
 ' Tiger Global',
 ' Tiger Global And Others',
 ' Tiger Global Management',
 ' Tiger Global and Apoletto Managers.',
 ' Times Internet',
 ' Times Internet Ltd',
 ' Toos N Daruvala',
 ' Toppan Printing',
 ' Touchstone Equities',
 ' Tracxn Labs',
 ' Tracxn Labs & Others',
 ' TransGlobal FZC',
 ' Transamerica and others.',
 ' Transmedia Capital',
 ' Trifecta Capital',
 ' True North',
 ' Trust Capital',
 ' Tuscan Ventures',
 ' Tushar Mittal',
 ' Tushar Singh',
 ' UC-RNT',
 ' Udaan Angels',
 ' Uday Kotak',
 ' Udayan Goyal',
 ' Unicorn India Ventures',
 ' Unicorn India Ventures and ISME ACE.',
 ' Unilazer Ventures',
 ' Unilever Ventures and Blume Ventures',
 ' Unitus Seed Fund',
 ' Utsav Somani',
 ' V Balakrishnan',
 ' VC Samsung NEXT',

In [57]:
df.to_csv('startup_cleaned.csv', index=False)