In [2]:
import pandas as pd

In [10]:
df = pd.read_csv('sales_data.csv')
df

    Order_ID        Date Region     Product  Quantity  Price  Revenue
0       1001  2024-01-01  North       Phone       1.0  15000    15000
1       1002  2024-01-02  South       Shirt       2.0    500     1000
2       1003  2024-01-03   East        Rice       3.0   1200     3600
3       1004  2024-01-04   West      Laptop       1.0  50000    50000
4       1005  2024-01-05  North       Jeans       2.0   1200     2400
5       1006  2024-01-06  South         Oil       1.0    800      800
6       1007         NaN   East  Headphones       2.0   2000     4000
7       1008  2024-01-08   West     T-Shirt       NaN    600     1800
8       1009  2024-01-09  North        Rice       1.0   1200     1200
9       1010  2024-01-10  South       Phone       1.0  14000    14000
10      1011  2024-01-11    NaN       Shirt       2.0    700     1400
11      1012  2024-01-12   West      Laptop       1.0  55000    55000
12      1013  2024-01-13  North         Oil       2.0    900     1800
13      1014  2024-01-14  South  Headphones       1.0   2500     2500
14      1015  2024-01-15   East       Jeans       2.0   1300     2600

In [5]:
# fetch the first five rows
df.head(5)

   Order_ID        Date Region Product  Quantity  Price  Revenue
0      1001  2024-01-01  North   Phone         1  15000    15000
1      1002  2024-01-02  South   Shirt         2    500     1000
2      1003  2024-01-03   East    Rice         3   1200     3600
3      1004  2024-01-04   West  Laptop         1  50000    50000
4      1005  2024-01-05  North   Jeans         2   1200     2400

In [6]:
# fetch the last 5 rows,
df.tail(5)

    Order_ID        Date Region     Product  Quantity  Price  Revenue
10      1011  2024-01-11   East       Shirt         2    700     1400
11      1012  2024-01-12   West      Laptop         1  55000    55000
12      1013  2024-01-13  North         Oil         2    900     1800
13      1014  2024-01-14  South  Headphones         1   2500     2500
14      1015  2024-01-15   East       Jeans         2   1300     2600

In [7]:
df.describe()

          Order_ID   Quantity         Price       Revenue
count    15.000000  15.000000     15.000000     15.000000
mean   1008.000000   1.666667   9793.333333  10473.333333
std       4.472136   0.723747  17980.484129  17647.114967
min    1001.000000   1.000000    500.000000    800.000000
25%    1004.500000   1.000000    850.000000   1600.000000
50%    1008.000000   2.000000   1200.000000   2500.000000
75%    1011.500000   2.000000   8250.000000   9000.000000
max    1015.000000   3.000000  55000.000000  55000.000000

In [8]:
df.dtypes

Order_ID    int64
Date          str
Region        str
Product       str
Quantity    int64
Price       int64
Revenue     int64
dtype: object

In [11]:
# finding an missing value in data
df.isnull()

    Order_ID   Date  Region  Product  Quantity  Price  Revenue
0      False  False   False    False     False  False    False
1      False  False   False    False     False  False    False
2      False  False   False    False     False  False    False
3      False  False   False    False     False  False    False
4      False  False   False    False     False  False    False
5      False  False   False    False     False  False    False
6      False   True   False    False     False  False    False
7      False  False   False    False      True  False    False
8      False  False   False    False     False  False    False
9      False  False   False    False     False  False    False
10     False  False    True    False     False  False    False
11     False  False   False    False     False  False    False
12     False  False   False    False     False  False    False
13     False  False   False    False     False  False    False
14     False  False   False    False     False  False    False

In [12]:
df.isnull().any()

Order_ID    False
Date         True
Region       True
Product     False
Quantity     True
Price       False
Revenue     False
dtype: bool

In [13]:
df.isnull().sum()

Order_ID    0
Date        1
Region      1
Product     0
Quantity    1
Price       0
Revenue     0
dtype: int64

In [14]:
# creating an cloumn which shows the mean value of cloumn where value is missing,

df['Quantity_FillNA'] = df["Quantity"].fillna(df['Quantity'].mean())
df

,Order_ID,Date,Region,Product,Quantity,Price,Revenue,Quantity_FillNA
0,1001,2024-01-01,North,Phone,1.0,15000,15000,1.000000
1,1002,2024-01-02,South,Shirt,2.0,500,1000,2.000000
2,1003,2024-01-03,East,Rice,3.0,1200,3600,3.000000
3,1004,2024-01-04,West,Laptop,1.0,50000,50000,1.000000
4,1005,2024-01-05,North,Jeans,2.0,1200,2400,2.000000
5,1006,2024-01-06,South,Oil,1.0,800,800,1.000000
6,1007,NaN,East,Headphones,2.0,2000,4000,2.000000
7,1008,2024-01-08,West,T-Shirt,NaN,600,1800,1.571429
8,1009,2024-01-09,North,Rice,1.0,1200,1200,1.000000
9,1010,2024-01-10,South,Phone,1.0,14000,14000,1.000000
10,1011,2024-01-11,NaN,Shirt,2.0,700,1400,2.000000
11,1012,2024-01-12,West,Laptop,1.0,55000,55000,1.000000
12,1013,2024-01-13,North,Oil,2.0,900,1800,2.000000
13,1014,2024-01-14,South,Headphones,1.0,2500,2500,1.000000
14,1015,2024-01-15,East,Jeans,2.0,1300,2600,2.000000

In [18]:
# renaming columns,

df = df.rename(columns={'Order_ID':'Order_No.'})
df.head()

,Order_No.,Date,Region,Product,Quantity,Price,Revenue,Quantity_FillNA
0,1001,2024-01-01,North,Phone,1.0,15000,15000,1.0
1,1002,2024-01-02,South,Shirt,2.0,500,1000,2.0
2,1003,2024-01-03,East,Rice,3.0,1200,3600,3.0
3,1004,2024-01-04,West,Laptop,1.0,50000,50000,1.0
4,1005,2024-01-05,North,Jeans,2.0,1200,2400,2.0

In [31]:
# Merging and joining dataframes

df1 = pd.DataFrame({'Keys':['A',"B",'C'],'Values1':[1,2,3]})
df2 = pd.DataFrame({'Keys':['A',"E",'B'],'Values2':[4,5,6]})

In [32]:
df1

  Keys  Values1
0    A        1
1    B        2
2    C        3

In [33]:
df2

  Keys  Values2
0    A        4
1    E        5
2    B        6

In [35]:
# Merfing dataframe with Key colunm
pd.merge(df1,df2,on="Keys",how="inner")

  Keys  Values1  Values2
0    A        1        4
1    B        2        6

In [37]:
# Merfing dataframe with Key colunm
pd.merge(df1,df2,on="Keys",how="outer")

  Keys  Values1  Values2
0    A      1.0      4.0
1    B      2.0      6.0
2    C      3.0      NaN
3    E      NaN      5.0