### Easy Level --Pandas-- Questions

In [1]:
import pandas as pd

In [33]:
# Question 1

data = {
    "Name": ["Aman", "Riya", "Sohan"],
    "Age": [20, 21, 19]
}

df = pd.DataFrame(data)
df

    Name  Age
0   Aman   20
1   Riya   21
2  Sohan   19

In [34]:
# Question 2

df.head(2)

   Name  Age
0  Aman   20
1  Riya   21

In [35]:
# Question 3

df['Name']

0     Aman
1     Riya
2    Sohan
Name: Name, dtype: str

In [36]:
# Question 4

print(df.iloc[0])

Name    Aman
Age       20
Name: 0, dtype: object

In [37]:
# Question 5

df[df['Age']>19]

   Name  Age
0  Aman   20
1  Riya   21

In [38]:
# Question 6

df['Marks'] = [80,90,55]
df

    Name  Age  Marks
0   Aman   20     80
1   Riya   21     90
2  Sohan   19     55

In [39]:
# Question 7

df['Marks'] = df['Marks'] + 5
df

    Name  Age  Marks
0   Aman   20     85
1   Riya   21     95
2  Sohan   19     60

In [40]:
# Question 8

print(df['Marks'].mean())

80.0

In [41]:
# Question 9

cf = df.sort_values(by='Marks',ascending=False)
cf

    Name  Age  Marks
1   Riya   21     95
0   Aman   20     85
2  Sohan   19     60

In [42]:
# Question 10

df = df.drop("Age",axis=1)
df

    Name  Marks
0   Aman     85
1   Riya     95
2  Sohan     60

In [48]:
# Question 11

data1 = {
    "Name": ["Aman", "Riya", "Sohan"],
    "Marks": [80, None, 85]
}

df1 = pd.DataFrame(data1)
df1

    Name  Marks
0   Aman   80.0
1   Riya    NaN
2  Sohan   85.0

In [46]:
df1['Marks'].fillna(0)

0    80.0
1     0.0
2    85.0
Name: Marks, dtype: float64

In [49]:
# Question 12

df1 = df1.dropna()
df1

    Name  Marks
0   Aman   80.0
2  Sohan   85.0

### Medium Level --Pandas-- Questions

In [56]:
import numpy as np

In [54]:
# Question 1

data3 = {
    "Name": ["Aman", "Riya", "Sohan", "Neha"],
    "Marks": [45, 82, 67, 30]
}

df2 = pd.DataFrame(data3)
df2

    Name  Marks
0   Aman     45
1   Riya     82
2  Sohan     67
3   Neha     30

In [57]:
df2['Result'] = np.where(df2['Marks'] >= 50 , 'Pass', 'Fail')
df2

    Name  Marks Result
0   Aman     45   Fail
1   Riya     82   Pass
2  Sohan     67   Pass
3   Neha     30   Fail

In [59]:
# Question 2

dt = {
    "Name": ["Aman", "Riya", "Sohan"],
    "City": ["bhopal", "delhi", "bhopal"]
}

df3 = pd.DataFrame(dt)
df3

    Name    City
0   Aman  bhopal
1   Riya   delhi
2  Sohan  bhopal

In [61]:
df3['City'] = df3['City'].str.title()
df3

    Name    City
0   Aman  Bhopal
1   Riya   Delhi
2  Sohan  Bhopal

In [2]:
# Question 3

data = {
    "Name": ["Aman", "Riya", "Sohan"],
    "Marks": [80, 95, 90]
}

df = pd.DataFrame(data)
df

    Name  Marks
0   Aman     80
1   Riya     95
2  Sohan     90

In [8]:
top_student = df.loc[df['Marks'].idxmax(),'Name']
print(top_student)

Riya

In [10]:
# Question 4

data = {
    "Marks": [35, 60, 75, 20, 90]
}

df = pd.DataFrame(data)
df

   Marks
0     35
1     60
2     75
3     20
4     90

In [12]:
failed_stu = df[df['Marks'] < 40]
print(len(failed_stu))

2

In [13]:
# Question 5

data = {
    "Price": [100, 200, 300],
    "Quantity": [2, 1, 4]
}

df = pd.DataFrame(data)
df

   Price  Quantity
0    100         2
1    200         1
2    300         4

In [15]:
df['Revenue'] = df['Price'] * df['Quantity']
df

   Price  Quantity  Revenue
0    100         2      200
1    200         1      200
2    300         4     1200